<?php

declare(strict_types=1);
/**
 * @var QuestionList $block
 * @var Question $question
 */

$questions = $block->getQuestions();

use Magebit\Faq\Block\QuestionList;
use Magebit\Faq\Model\Question;

?>

<div id="element"
     data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
    <?php
    if (!empty($questions)): ?>
        <?php
        foreach ($questions as $question): ?>
            <div class="magebit-faq-collapsible-title" data-role="collapsible">
                <div data-role="trigger">
                    <span><?= $block->escapeHtml(__($question['question'])) ?></span>
                </div>
            </div>
            <div class="magebit-faq-collapsible-content"
                 data-role="content"><?= $block->escapeHtml(__($question['answer'])) ?></div>
        <?php
        endforeach; ?>
    <?php
    endif; ?>
</div>
